# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: get last deployment id
          command: >
            aws cloudformation 
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" 
            --no-paginate --output text > ~/last-id.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - last-id.txt

  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: run cloudformation to create S3 bucket
          command: >
            aws cloudformation deploy --template-file bucket.yml 
            --stack-name "jimstack-${CIRCLE_WORKFLOW_ID:0:7}" 
            --parameter-overrides PipelineID="jimstack-${CIRCLE_WORKFLOW_ID:0:7}"

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: promote to production
          command: >
            aws cloudformation deploy --template-file cloudfront.yml 
            --stack-name production-distro 
            --parameter-overrides PipelineID="jimstack-${CIRCLE_WORKFLOW_ID}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: clean up old front end
          command: |
            OldPipelineID = `cat last-id.txt`
            echo $OldPipeLineID
            PreviousPipelineID = "production-distro"
            echo $PreviousPipelineID
            aws s3 rm "s3://${OldPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"

workflows:
  my_workflow:
    # Runs the jobs in order
    jobs:
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires: 
            - create_and_deploy_front_end
      - promote_to_production:
          requires: 
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires: 
            - promote_to_production